---
- name: Create PVs for Users
  hosts: nfs
  become: true
  tasks:
     - name: Create Dirs
       file: 
        dest: /srv/nfs/user-vols/pv{{ item }} 
        state: directory
        owner: nfsnobody
        group: nfsnobody
        mode: 0777
       with_sequence: start=1 end=50
     
     - name: Create File openshift-uservols.exports
       file: 
        dest: /etc/exports.d/openshift-uservols.exports
        owner: nfsnobody
        group: nfsnobody
        mode: 0777
        state: touch

     - name: Exports Vars
       lineinfile: 
         path: /etc/exports.d/openshift-uservols.exports
         line: "/srv/nfs/user-vols/pv{{ item }} *(rw,root_squash)"
       with_sequence: start=1 end=50

     - name: Restarting NFS Server
       shell: systemctl restart nfs-server

- name: Create PV Def files
  hosts: localhost
  tasks:
     - name: Register GUID variable
       shell: hostname|awk -F. '{print $2}'
       register: guid_val

     - name: Create PVS Directory
       file: 
        dest: ./pvs
        state: directory

     - name: Create 25 definitions files for PVs 5G size and ReadWriteOnce
       template:
         src: ./templates/pv_5g.j2
         dest: ./pvs/pv{{ item }}.yml
       with_sequence: start=1 end=25

     - name: Create 25 definitions files for PVs 10G size and ReadWriteMany
       template:
         src: ./templates/pv_10g.j2
         dest: ./pvs/pv{{ item }}.yml
       with_sequence: start=26 end=50
    
     - name: Create 25 definitions files for PVs 10G size
       shell: cat ./pvs/* | oc create -f -
