- name: Replace Variables in Hosts file
  hosts: localhost
  become: true
  vars_files:
    - feature_enablers_configs.yaml
  tasks:
     - name: Sudo
       shell: sudo -s
     - name: Replace openshift release version
       replace:
          path: ./hosts
          regexp: '{{ item.attribute|upper }}'
          replace: '{{ item.value }}'
       with_items:
         - "{{ host_inventory_vars }}"
     - name: Replace GUID in the hosts file
       shell: sed -i 's/GUID/'{{ GUID }}'/g' ./hosts
     - name: Copy a new hosts file to /etc/ansible/hosts
       copy: 
         src: ./hosts
         dest: /etc/ansible/hosts
          
    
