---
- name: Create Project
  hosts: localhost
  tasks:
     - name: Create namespace smoke-test
       shell: oc new-project smoke-test

     - name: Add new application to namespace
       shell: oc new-app nodejs-mongo-persistent

     - name: wait for pods to come up
       shell: oc get pods -o json
       register: openshift_get_pods
       until: openshift_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running", "Completed"]
    