
- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin